USE [LIGOLAB_37_SUMMIT]
SELECT
lo.ACCESSION AS 'Accession',
lotr.LAB_TEST_RESULT_ACCESSION AS 'Result ID',
CONCAT(lp.LAST_NAME, ', ', lp.FIRST_NAME) AS 'Patient Name',
lp.DOB AS 'Date of Birth'
FROM
LAB_ORDER lo
INNER JOIN LAB_ORDER_TEST_RESULT lotr ON lotr.LAB_ORDER_ID = lo.LAB_ORDER_ID
INNER JOIN LAB_PATIENT lp on lp.LAB_PATIENT_ID = lo.LAB_PATIENT_ID